AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Serverless application.

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: lambda_logs_policy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: logs:CreateLogGroup
              Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*
            - Effect: Allow
              Action:
                - s3:PutLifecycleConfiguration
              Resource: "*"
            - Effect: Allow
              Action:
                - cloudformation:*
              Resource:
                - !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/data-lake-s3-*/*
                - !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/data-lake-kinesis-*/*
                - !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/data-lake-kinesis-trigger-*/*

  DeleteStackLambda:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: latest
      CodeUri: lambda
      FunctionName: dala-lake-control-delete-stack
      Handler: deploy-stack.handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.7
      Timeout: 600

  DeleteStackLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${DeleteStackLambda}
      RetentionInDays: 7

  DeleteS3ObjectsLambda:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: latest
      CodeUri: lambda
      FunctionName: dala-lake-control-delete-s3-objects
      Handler: delete-all-objects.handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.7
      Timeout: 600

  DeleteS3ObjectsLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${DeleteS3ObjectsLambda}
      RetentionInDays: 7

  StepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: [ !GetAtt [ DeleteStackLambda, Arn ], !GetAtt [ DeleteS3ObjectsLambda, Arn ] ]

  StepFunction:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      DefinitionString:
        !Sub
          - |-
            {
              "StartAt": "DeleteStackKinesisTriggerState",
              "States": {
                "DeleteStackKinesisTriggerState": {
                  "Type": "Task",
                  "Resource": "${DeleteStackLambdaArn}",
                  "InputPath": "$",
                  "Parameters": {
                    "uri.$": "$.uri",
                    "stack_name": "kinesis-trigger-stack",
                    "template_name": "kinesis-trigger-template.yml"
                  },
                  "OutputPath": "$",
                  "Next": "DeleteStackKinesisState",
                  "Catch": [
                    {
                      "ErrorEquals": ["States.ALL"],
                      "Next": "DeleteErrorState"
                    }
                  ]
                },
                "DeleteStackKinesisState": {
                  "Type": "Task",
                  "Resource": "${DeleteStackLambdaArn}",
                  "InputPath": "$",
                  "Parameters": {
                    "uri.$": "$.uri",
                    "stack_name": "kinesis-stack",
                    "template_name": "kinesis-template.yml"
                  },
                  "OutputPath": "$",
                  "Next": "DeleteS3ObjectsState",
                  "Catch": [
                    {
                      "ErrorEquals": ["States.ALL"],
                      "Next": "DeleteErrorState"
                    }
                  ]
                },
                "DeleteS3ObjectsState": {
                  "Type": "Task",
                  "Resource": "${DeleteS3ObjectsLambdaArn}",
                  "InputPath": "$",
                  "Parameters": {
                    "uri.$": "$.uri",
                    "life_cycle_days": 1
                  },
                  "OutputPath": "$",
                  "Next": "WaitForS3Empty",
                  "Catch": [
                    {
                      "ErrorEquals": ["States.ALL"],
                      "Next": "DeleteErrorState"
                    }
                  ]
                },
                "WaitForS3Empty": {
                  "Type": "Wait",
                  "Seconds": 10,
                  "Next": "DeleteStackS3State"
                },
                "DeleteStackS3State": {
                  "Type": "Task",
                  "Resource": "${DeleteStackLambdaArn}",
                  "InputPath": "$",
                  "Parameters": {
                    "uri.$": "$.uri",
                    "stack_name": "s3-stack",
                    "template_name": "s3-template.yml"
                  },
                  "OutputPath": "$",
                  "Catch": [
                    {
                      "ErrorEquals": ["States.ALL"],
                      "Next": "DeleteErrorState"
                    }
                  ],
                  "End": true
                },
                "DeleteErrorState": {
                  "Type": "Fail"
                }
              }
            }
          - {DeleteStackLambdaArn: !GetAtt [ DeleteStackLambda, Arn ], DeleteS3ObjectsLambdaArn: !GetAtt [ DeleteS3ObjectsLambda, Arn ]}
      RoleArn: !GetAtt [StepFunctionRole, Arn]
      StateMachineName: data-lake-control-delete-log-type
Outputs:
  StepFunction:
    Description: StepFunction
    Value: !Ref StepFunction
