AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Env:
    Type: String
    Default: dev
Resources:
  S3BucketLog:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub ys-dev-web-cloudfront-log-${Env}
      LifecycleConfiguration:
        Rules:
        - Status: Enabled
          ExpirationInDays: 14
    DeletionPolicy: Delete
  S3BucketOrigin:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub ys-dev-web-cloudfront-origin-${Env}
      LifecycleConfiguration:
        Rules:
        - Status: Enabled
          ExpirationInDays: 14
    DeletionPolicy: Delete
  BucketPolicy:
    DependsOn: OriginAccessIdentity
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3BucketOrigin
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${S3BucketOrigin}/*
            Principal:
              AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${OriginAccessIdentity}
  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Origin Access Identity
  CloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub ${S3BucketOrigin}.s3.amazonaws.com
            Id: myS3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${OriginAccessIdentity}
        Enabled: true
        Comment: CloudFront Test.
        Logging:
          IncludeCookies: false
          Bucket: !Sub ${S3BucketLog}.s3.amazonaws.com
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: myS3Origin
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: allow-all
        PriceClass: PriceClass_100
