# source code: src/base-cloudmap-lambda.py
Parameters:
  Env:
    Type: String
    Default: dev
Resources:
  TestDynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ServiceId
          AttributeType: S
      KeySchema:
        - AttributeName: ServiceId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  CloudMapNameSpace:
    Type: AWS::ServiceDiscovery::HttpNamespace
    Properties:
      Name: sample-biz-system
  CloudMapService:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Name: test-application
      NamespaceId: !Ref CloudMapNameSpace
  ExampleInstance:
    Type: AWS::ServiceDiscovery::Instance
    Properties:
      InstanceAttributes:
        env: !Ref Env
      InstanceId: !Ref TestDynamoDB
      ServiceId: !Ref CloudMapService