AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Env:
    Type: String
    Default: dev
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ys-dev-web-kinesis-firehose-${Env}
      LifecycleConfiguration:
        Rules:
        - Status: Enabled
          ExpirationInDays: 1
    DeletionPolicy: Delete
  Kinesis:
    DependsOn: KinesisRolePolicy
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      ExtendedS3DestinationConfiguration:
        BucketARN: !Sub arn:aws:s3:::${S3Bucket}
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 1
        CompressionFormat: UNCOMPRESSED
        Prefix: firehose/
        RoleARN: !GetAtt KinesisRole.Arn
  KinesisRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole
  KinesisRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: firehose_delivery_policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: s3:*
            Resource: !Sub arn:aws:s3:::${S3Bucket}*
      Roles:
        - !Ref KinesisRole
Outputs:
  Kinesis:
    Value: !Ref Kinesis
    Export:
      Name: !Sub ys-dev-web-kinesis-firehose-${Env}