AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  UploadedS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ys-dev-web-kinesis-firehose-uploaded
      LifecycleConfiguration:
        Rules:
        - Status: Enabled
          ExpirationInDays: 7
    DeletionPolicy: Delete
  TransformedS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ys-dev-web-kinesis-firehose-transformed
      LifecycleConfiguration:
        Rules:
        - Status: Enabled
          ExpirationInDays: 7
    DeletionPolicy: Delete
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://ys-dev-web-kinesis-firehose-dev/5e87aa72b41e25ed06130bdc3d84cff5
      Handler: devide-json-stream-sam.handler
      FunctionName: devide-json-stream
      Runtime: python3.7
      Timeout: 300
      MemorySize: 256
      Role:
        Fn::GetAtt:
        - LambdaRole
        - Arn
      Events:
        JsonStreamDevideEvent:
          Type: S3
          Properties:
            Bucket:
              Ref: UploadedS3Bucket
            Events: s3:ObjectCreated:*
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
  Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: s3-logs-access-policy
      Roles:
      - Ref: LambdaRole
      PolicyDocument:
        Statement:
        - Effect: Allow
          Resource:
            Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/devide-json-stream:*
          Action:
          - logs:*
        - Effect: Allow
          Resource:
            Fn::Sub: arn:aws:s3:::${UploadedS3Bucket}*
          Action:
          - s3:*
        - Effect: Allow
          Resource:
            Fn::Sub: arn:aws:s3:::${TransformedS3Bucket}*
          Action:
          - s3:*
